### PR TITLE
Fix broken multiblocks - remove hacky `polluteEnvironment()`

### LINKED ISSUE #190: I cant get any multiblocks to work [1.6.110-final]
ISSUE CONTENT;
GT version 5.09.32
Ic2 version 2-2.2.828a-experimental
I play gtnh, and after an update I can't get any of the gt++ multiblocks to work that I have. My plate bender broke, and later the abf broke in the same way. They will turn on then off immediately. I can soft mallet them, but they never complete a recipe. They have the right amount of power and the recipe is right. I tried remaking the controller block, but that didn't work. 
Kind of a major issue as I can't use any of the multiblocks. I need a bunch of uu and I was thinking of using the uu multiblock

### PR DESCRIPTION
**Pull request by codewarrior0**
This code path should never have worked. `getDeclaredField()` only searches the given class and not any of its superclasses - because `mPollution` is declared in a superclass, `null` will always be returned.

Fixes #190 #186 #176

### CODE REVIEW

**Comment by draknyte1** [comment]
You can't remove this because it breaks .08 support..

**Comment by codewarrior0** [comment]
Are you sure about that? .08 has its own implementation of `polluteEnvironment()` which should be working fine.

**Comment by draknyte1** [comment]
.08 does not have pollution at all.

**Comment by codewarrior0** [comment]
Your build scripts reference version 5.08.33, [which I acquired here](https://minecraft.curseforge.com/projects/gregtech-5-unofficial/files/2330137), and it appears to implement pollution at least partially.

image

**Pull request merged**
