### PR TITLE
Tree Farm does reduced output

### PR DESCRIPTION
**Pull request by extrn**
forCounter haven't been updated

### CODE REVIEW

**Comment by draknyte1** [comment]
Are you doing anything else with this Pull Request?

**Comment by extrn** [comment]
I think I don't
But this is my first pull request, so I could be made something wrong :)

**Comment by draknyte1** [comment]
Just was wondering if this was the only change you wanted to make, otherwise you've done everything correctly. :)

**Comment by extrn** [comment]
ok, that's all for now :)

**Pull request merged**
