### PR TITLE
Fix several broken machine and casing recipes (wrong gear type)

### PR DESCRIPTION
**Pull request by codewarrior0**
Thermal Refinery Controller
Fission Fuel Refinery Controller and Casings
LFTR Casings

### CODE REVIEW

**Comment by codewarrior0** [comment]
I'm not sure. GT5-U registers its gears first as `gearGt*` and then using a, um, `registerOre` event handler, re-registers them as `gear*`. I didn't see anything similar in your code, and you seem to be using a separate Material class too.

**Comment by draknyte1** [comment]
My material system is irrelevant. 

The fact that they used to get auto tagged correctly and now they don't indicates a GT change. Otherwise those recipes never would've worked, which is simply not the case.

**Comment by codewarrior0** [comment]
I mean, I only brought it up because it looks like the auto tagging [relies on finding a `Materials` instance for the material...](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_Proxy.java#L1133-L1203)

**Comment by codewarrior0** [comment]
Oh, also, these recipes are missing when running on GT 5.08.33.

**Comment by codewarrior0** [comment]
Whoops, false start, had to comment out some stuff (powderbarrel, osmium coins) first but I actually got it to load under 5.08.33 this time. Aaaaand....

Recipes still gone.

**Comment by draknyte1** [comment]
The stuff from the last few days I haven't ran against .08 compat yet. 

My handling for powder barrels in CI.java should've been sufficient for .08.

**Comment by draknyte1** [comment]
Want me to merge this in now?

**Comment by codewarrior0** [comment]
No objections here.

**Pull request merged**
