### PR TITLE
changing Wind Rotor /shaft recipes for GTNH

### PR DESCRIPTION
**Pull request by Dream-Master**
@draknyte1 I added recipe for my Modpack and i added Shaft recipe make out of Blocks like the IC2 recipes.

### CODE REVIEW

**Comment by draknyte1** [comment]
I was fairly sure I commented on this...
But anyway, does this work correctly?

**Comment by Dream-Master** [comment]
In my game it works. I not test it without my mod.(Core Mod)

**Comment by draknyte1** [comment]
I'll give it a test this afternoon and merge it in.

**Comment by Dream-Master** [comment]
Try to merge your new commits destroy my master branch. I will setup it again

**Comment by Dream-Master** [comment]
@draknyte1 There was a bracket cause a conflict hope thats all.

**Comment by draknyte1** [comment]
I'm not done working on that stuff. Easier to not merge it

**Comment by Dream-Master** [comment]
@draknyte1 did you need a new pull request with only my changes ?

**Comment by draknyte1** [comment]
That's the idea of how PRs work, afaik. 
At least they're minimal.

**Comment by Dream-Master** [comment]
Will do when i be back home.

**Comment by Dream-Master** [comment]
Ok i made a new pull request

**Pull request closed without merging**
