### PR TITLE
re-tiered Tanks a bit for GTNH pack

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Comment by draknyte1** [comment]
Don't add a gitignore, I already have one in each of my workspaces. 

If adding GTNH recipes, follow the format left there. Change the plate/pipe tierX variables and place them into the recipes, don't use items directly.

**Comment by Dream-Master** [comment]
using "plateSteel" as an example ok?

**Comment by draknyte1** [comment]
Why did you rename circuits in the master declaration? I'm not supporting the changes made to circuits in .28 yet nor will I for a while..

Take the tiers you want to change, change their values in the GTNH block.

PlateTier1 = "plateSteel";
Then use plateTier1 in recipes.

**Comment by Dream-Master** [comment]
Ok but i need maybe 2 different plates at 1 Level. How should i name it?
adding the primitive Circuit via Itemlist.CircuitPrimitive (Gergtech) not workong thats why i try with the rename. Any idea how to add it better?

**Comment by draknyte1** [comment]
Use the tiers you aren't actually using. So, instead of 1-6, use 1-10, where 10 is the highest tier material you want to use.~

The recipe builder uses oreDict names fine, so if you make circuitTier1 = "circuitPrimitive" it will be. There is never really a need to specify an exact item, like new ItemStack(Items.water_bucket, 1). If you REALLY have to, make an ItemStack variable, named bucketWater = ItemUtils.getSimpleStack(Items.water_bucket, 1); and re-use it. Calling things more than once that aren't already defined variables adds to memory usage, however miniscule. Good practice dictates you only make an object once and re-use it, that's the idea of OOP.

**Comment by Dream-Master** [comment]
Sure will try it out later and update the files. The best way to get better in java is to make mistakes and learn from it (get help from you or other be better in java then me)

**Comment by Dream-Master** [comment]
bucketWater = ItemUtils.getSimpleStack(Items.water_bucket, 1); i cant using have to define it before.

**Comment by Dream-Master** [comment]
circuitTier1 = "circuitPrimitve"; not works sadly

**Comment by draknyte1** [comment]
So define the itemstack for a bucket, just keep it in the GTNH block.

**Comment by draknyte1** [comment]
This is looking good mate, Let me merge it in.

**Pull request merged**
