### PR TITLE
Gtnh-rotos

### PR DESCRIPTION
**Pull request by Dream-Master**
Ok this should work hopfully

### CODE REVIEW

**Comment by draknyte1** [comment]
https://github.com/GTNewHorizons/GTplusplus/blob/0634380cb887caec3bd09635f0bc524f9c67cc40/src/Java/gtPlusPlus/xmod/ic2/recipe/RECIPE_IC2.java#L145-L149
```
if (LoadedMods.EnderIO && CORE.GTNH) {
			Utils.LOG_INFO("Added recipe for GT5 Extruder: Windmill Shaft [Energetic]");
		} else {
			Utils.LOG_INFO("Added recipe for GT5 Extruder: Windmill Shaft [Magnalium]");
		}
```

This won't work.

**Comment by draknyte1** [comment]
https://github.com/GTNewHorizons/GTplusplus/blob/0634380cb887caec3bd09635f0bc524f9c67cc40/src/Java/gtPlusPlus/xmod/ic2/recipe/RECIPE_IC2.java#L192
This should be an else, no need to do an if(CORE.GTNH) check at all, because it's going to be true if the first if is false.

**Comment by draknyte1** [comment]
Fixed it here - https://pastebin.com/3m9drVdx
Recommit that and everything should be right to merge.

**Comment by Dream-Master** [comment]
Ok sec

**Comment by Dream-Master** [comment]
Ok but you remove the Extruder recipe which i like to have in my mod. Should i add this recipes with if Core GTNH loaded?

**Comment by draknyte1** [comment]
Alright, suggestion;
```
if (!CORE.GTNH){
GT_Values.RA.addExtruderRecipe(GT_Utility.copyAmount(9L, block_T1), GregtechItemList.Shape_Extruder_WindmillShaft.get(0L, new Object[0]), shaft_T1, 2560, 250);
		}
		else {
GT_Values.RA.addExtruderRecipe(GT_Utility.copyAmount(1L, shaft_block_T1), GregtechItemList.Shape_Extruder_WindmillShaft.get(0L, new Object[0]), shaft_T1, 2560, 250);
		}
```
Can become;
```
GT_Values.RA.addExtruderRecipe(GT_Utility.copyAmount(9L, block_T1), GregtechItemList.Shape_Extruder_WindmillShaft.get(0L, new Object[0]), shaft_T1, 2560, 250);
if (CORE.GTNH){
GT_Values.RA.addExtruderRecipe(GT_Utility.copyAmount(1L, shaft_block_T1), GregtechItemList.Shape_Extruder_WindmillShaft.get(0L, new Object[0]), shaft_T1, 2560, 250);
		}
```

**Comment by draknyte1** [comment]
I guess we can leave block recipes for non-GTNH.
Apologies for being a pain, but revert https://github.com/draknyte1/GTplusplus/pull/93/commits/290207067ee39b29b3d3cce0e2862602d8ea18ca and it'll be right to merge from what I can see.

**Comment by Dream-Master** [comment]
ok done

**Pull request merged**
