### PR TITLE
[GTNH]fix for LCR recipes

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Comment by draknyte1** [comment]
`addChemicalRecipeForBasicMachineOnly` Isn't 5.08 compatible... So you'll have to remake this again..

**Comment by Dream-Master** [comment]
That is why I add the recipe only for my pack not for the main repo.

**Comment by Dream-Master** [comment]
Otherwise I can't fix it and we have further issues with it. One thing more I remove all this recipes in GTNH and add it via core mod.

**Comment by Dream-Master** [comment]
@draknyte1 i will put your fluids implement in core mod  and disable recipe in gt++ (if core mod is loaded) so long the problem are exists that chemical reactor recipes be automaticly in LCR.

**Comment by draknyte1** [comment]
I'll fix it later and just call via reflection.

**Comment by Dream-Master** [comment]
i am on an update allready push it in a few mins.

**Pull request closed without merging**
